-- Flappy13 v0.2.7.2b-dev1 - server-issued verified-run tickets.
-- Run after 001_profiles.sql and 002_best_score_sync.sql.
-- Safe to run more than once from the Supabase SQL Editor.

create table if not exists public.verified_runs (
  run_id uuid primary key default gen_random_uuid(),
  player_id uuid not null references auth.users(id) on delete cascade,
  seed integer not null,
  physics_version text not null,
  status text not null default 'issued',
  issued_at timestamptz not null default now(),
  submitted_at timestamptz,
  resolved_at timestamptz,
  replay_hash text,
  terminal_tick integer,
  tap_ticks integer[],
  verified_score integer,
  collision text,
  rejection_code text,

  constraint verified_runs_physics_version_format
    check (physics_version ~ '^flappy13-physics-v[1-9][0-9]*$'),
  constraint verified_runs_status_valid
    check (status in ('issued', 'verified', 'rejected')),
  constraint verified_runs_replay_hash_valid
    check (replay_hash is null or replay_hash ~ '^[0-9a-f]{64}$'),
  constraint verified_runs_terminal_tick_valid
    check (terminal_tick is null or terminal_tick between 0 and 216000),
  constraint verified_runs_tap_count_valid
    check (tap_ticks is null or cardinality(tap_ticks) between 1 and 216001),
  constraint verified_runs_score_valid
    check (verified_score is null or verified_score between 0 and 2147483647),
  constraint verified_runs_collision_valid
    check (collision is null or collision in ('ground', 'upper-pipe', 'lower-pipe')),
  constraint verified_runs_state_shape_valid
    check (
      (
        status = 'issued'
        and submitted_at is null
        and resolved_at is null
        and replay_hash is null
        and terminal_tick is null
        and tap_ticks is null
        and verified_score is null
        and collision is null
        and rejection_code is null
      )
      or
      (
        status = 'verified'
        and submitted_at is not null
        and resolved_at is not null
        and replay_hash is not null
        and terminal_tick is not null
        and tap_ticks is not null
        and verified_score is not null
        and collision is not null
        and rejection_code is null
      )
      or
      (
        status = 'rejected'
        and submitted_at is not null
        and resolved_at is not null
        and replay_hash is not null
        and verified_score is null
        and collision is null
        and rejection_code is not null
      )
    )
);

create index if not exists verified_runs_player_issued_idx
  on public.verified_runs (player_id, issued_at desc);

create index if not exists verified_runs_verified_score_idx
  on public.verified_runs (verified_score desc, resolved_at asc)
  where status = 'verified';

alter table public.verified_runs enable row level security;

-- Tickets, seeds, replay payloads and verification decisions are server-owned.
-- The future leaderboard will expose a deliberately restricted view/RPC rather
-- than granting browser clients direct access to this table.
revoke all on table public.verified_runs from public, anon, authenticated;

comment on table public.verified_runs is
  'Server-owned run tickets and authoritative verification results.';
comment on column public.verified_runs.seed is
  'Signed int32 seed generated by the run-start Edge Function.';
comment on column public.verified_runs.physics_version is
  'Deterministic simulation contract, independent from the PWA release number.';
